public enum AbilityKind
{
    nothing,

    //戦士基本職初級
    beginner_swordmanship,
    beginner_spearmanship,
    beginner_bojutsu,
    beginner_battleaxe,
    beginner_shieldmanship,
    beginner_martialart,
    //戦士基本職中級
    intermediate_swordmanship,
    intermediate_spearmanship,
    intermediate_bojutsu,
    intermediate_battleaxe,
    intermediate_shieldmanship,
    intermediate_martialart,
    //戦士基本職上級
    advanced_swordmanship,
    advanced_spearmanship,
    advanced_bojutsu,
    advanced_battleaxe,
    advanced_shieldmanship,
    advanced_martialart,

    //魔術士基本職初級
    primary_fire_magic,
    primary_water_magic,
    primary_wind_magic,
    primary_earth_magic,
    primary_thunder_magic,
    primary_ice_magic,
    primary_light_magic,
    primary_dark_magic,
    //魔術士基本職中級
    intermediate_fire_magic,
    intermediate_water_magic,
    intermediate_wind_magic,
    intermediate_earth_magic,
    intermediate_thunder_magic,
    intermediate_ice_magic,
    intermediate_light_magic,
    intermediate_dark_magic,
    //魔術士基本職上級
    advanced_fire_magic,
    advanced_water_magic,
    advanced_wind_magic,
    advanced_earth_magic,
    advanced_thunder_magic,
    advanced_ice_magic,
    advanced_light_magic,
    advanced_dark_magic,

    //使役者基本職初級
    animal_handling,
    //使役者基本職中級
    beast_tamer,
    insect_handling,
    bird_handling,
    elementalor,
    summon_fairy,
    summon_familiar,
    //使役者基本職上級
    monster_tamer,
    summoner,

    //共通基本職（戦士初級）
    hoodlum,
    seclusion,
    //共通基本職（戦士中級）
    thief,
    assassin,
    //共通基本職（戦士上級）
    ninja,

    //共通基本職（魔術師初級）
    black_mage,
    believer,
    //共通基本職（魔術師中級）
    necromancer,
    priest,
    fanatic,
    //共通基本職（魔術師上級）
    demonolater,

    //共通基本職（生産職初級）
    pharmacist,
    use_tools,
    life_magic,
    //共通基本職（生産職中級）
    doctor,
    crafter,
    whitesmith,
    magicrafter,
    enchanter,
    //共通基本職（生産職上級）
    blacksmith,
    machine_engineer,
    alchemist,
    high_enchanter,

}
