namespace MainAction
{
    public class ActionEnum
    {
        public enum Instant
        {
            nothing,
            //フェーズ１（入学前）
            weeding,
            intensive_training,
            eat_anchovy_sandwich,
            eat_filet_o_fish,
            drink_herb_tea,
            rune_generation,
            runic_carving,
            split_firewood,
            sell_firewood,
            sell_bread,
            //フェーズ２（学校）
            //アビリティアクション
            mugged,
            devotion,
            take_medicine,

        }

        public enum Loop
        {
            nothing,
            //常用
            rest,
            pray,
            //フェーズ１（入学前）
            farmwork,
            harvest_wheat,
            grow_herb,
            lumberjack,
            craft_magi_stone,
            //フェーズ２（学校）
            manual_labor,
            desk_work,
            service_trade,
            //アビリティアクション
            pickpocket,
            dispense_medicines,

        }

        public enum Upgrade
        {
            nothing,
            //フェーズ１（入学前）
            talk_fatherA,
            talk_fatherB,
            talk_fatherC,
            talk_fatherD,
            //父の道場
            training,
            sword_practice,
            spear_practice,
            rod_practice,
            //母の書斎
            mental_training,
            read_fire_spellbook,
            read_water_spellbook,
            read_wind_spellbook,
            read_earth_spellbook,
            //村の広場
            play_with_cat,
            learn_use_tools,
            succession_life_magic,
            //純アップグレード
            buy_wallet,
            study_in_church,
            buy_bag,
            rune_augmentation,
            buy_fire_spellbook,
            //少女イベント
            girl_is_crying,
            pick_flowers,
            punish_the_bad_kids,
            thank_you,
            ill_get_you_for_this,
            //進学
            warrior_school,
            sorcerer_school,
            tamer_school,
            leave_the_town,
            //フェーズ２（学校）
            academic_city,
            into_a_dormitory,
            entrance_ceremony,
            //攫われイベント
            norns_room,
            desolate_room,
            rumor,
            //フリークエスト
            delivery_of_fur,
            house_clean_up,
            get_rid_of_rat,
            wholesaler_of_drugs,
            in_cellar,

            //授業
            sword_classwork,
            spear_classwork,
            rod_classwork,
            fire_magic_classwork,
            water_magic_classwork,
            wind_magic_classwork,
            earth_magic_classwork,
            animal_handling_classwork,
            use_tools_classwork,
            life_magic_classwork,

            //戦士
            apprentice_warrior,
            warrior,
            soldier,
            mercenary,
            trooper,
            knight,
            slayer,
            fighter,
            //魔導士
            apprentice_sorcerer,
            sorcerer,
            wizard,
            warlock,
            high_sorcerer,
            priest,
            conjurer,
            black_mage,
            //テイマー
            apprentice_tamer,
            tamer,
            beast_tamer,
            elementaler,
            monster_tamer,
            summoner,
            //生産職
            crafter,
            iron_crafter,
            magicrafter,
            weapon_maker,
            alchemist,

        }
    }
}
