public enum SkillKind
{
    nothing,
    normalAttack,
    normalAttack_npc1,
    //レベル解放スキル
    punch,
    impact,
    throwing,
    boost,
    //戦士
    right_slash,
    left_upper_slash,
    cooking_sandwich,//生産
    stab,
    upper_slash,
    spearfishing,//生産
    left_small_swing,
    parry,
    knead_dough,//生産
    /*helm_splitter,
    left_whirlslash,
    guard,
    absolute_defense,
    dodge_step,
    right_spinkick,
    */
    //魔導士
    fireball,
    hot_body,
    create_charcoal,//生産
    burning_shot,
    waterball,
    cure_water,
    catch_fish,//生産
    hydro_blade,
    air_cutter,
    wind_step,
    create_firewood,//生産
    air_bazooka,
    stone_bullet,
    earth_wall,
    grow_wheat,//生産
    rock_press,
    /*electric_arrow,
    electric_step,
    ice_arrow,
    ice_shell,
    holy_circle,
    dark_wave,
    */
    //テイマー
    animal_attack,
    picking_up_coins,
    mad_animal,
    //複合スキル
    flame_slash,
    mud_shot,
    storm_spike,
    animal_rush,

}
